import { registerEnumType } from "@nestjs/graphql";

export enum Message {
    SOMETHING_WENT_WRONG = 'SOMETHING WENT WRONG',
    NO_DATA_FOUND = 'NO_DATA_FOUND',
    CREATE_FAILED = 'CREATE_FAILED',
    UPDATE_FAILED = 'UPDATE_FAILED',
    REMOVE_FAILED = 'REMOVE_FAILED',
    UPLOAD_FAILED = 'UPLOAD_FAILED',
    BAD_REQUEST = 'BAD_REQUEST',

    USED_MEMBER_NICK_OR_PHONE = "Already used member nick or phone",
    NO_MEMBER_NICK = 'NO_MEMBER_NICK',
    BLOCKED_USER = 'BLOCKED_USER',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
    TOKEN_NOT_EXIST = 'TOKEN_NOT_EXIST',
    ONLY_SPECIFIC_ROLES_ALLOWED = 'ONLY_SPECIFIC_ROLES_ALLOWED',
    NOT_ALLOWED_REQUEST = 'NOT_ALLOWED_REQUEST',
    PROVIDE_ALLOWED_FORMAT = 'PROVIDE_ALLOWED_FORMAT',
    SELF_SUBSCRIPTION_DENIED = 'SELF_SUBSCRIPTION_DENIED',
}

export enum Direction {
    ASC = 1,
    DESC = -1,
}

registerEnumType(Direction, {name: "Direction"});